Add options to utest that will be used in CI

diff --git a/tests/utest b/tests/utest
--- a/tests/utest
+++ b/tests/utest
@@ -57,6 +57,61 @@ cleanup() {
   exit
 }
 
+build_utests() {
+  # build_file specifies compilation options
+  build_file='utest.bld'
+  [[ -f ${build_file} ]] || error "${build_file} does not exist"
+
+  compile_log=${PATHRT}/Compile_ut_$MACHINE_ID.log
+  rm -f fv3_*.exe modules.fv3_* ${compile_log}
+
+  while IFS="|" read model comp_opt; do
+    model_found=false
+    model=$(echo $model | sed -e 's/^ *//' -e 's/ *$//')
+    comp_opt=$(echo $comp_opt | sed -e 's/^ *//' -e 's/ *$//')
+    if [[ $model == ${TEST_NAME} ]]; then
+      base_opt=${comp_opt}
+      model_found=true
+      break
+    fi
+  done < ${build_file}
+  if [[ ${model_found} == false ]]; then
+    error "Build options for $TEST_NAME not found. Please edit utest.bld."
+  fi
+
+  for name in $ut_compile_cases; do
+    case $name in
+      std)
+        NEMS_VER=${base_opt}
+        ;;
+      32bit)
+        if [[ ${base_opt} =~ "32BIT=Y" ]]; then
+          NEMS_VER=$(echo ${base_opt} | sed -e 's/32BIT=Y/32BIT=N/')
+        elif [[ ${base_opt} =~ "32BIT=N" ]]; then
+          NEMS_VER=$(echo ${base_opt} | sed -e 's/32BIT=N/32BIT=Y/')
+        else
+          NEMS_VER="${base_opt} 32BIT=Y"
+        fi
+        ;;
+      debug)
+        NEMS_VER="${base_opt} 32BIT=Y DEBUG=Y"
+        ;;
+    esac
+    NEMS_VER=$(echo ${NEMS_VER} | sed -e 's/^ *//' -e 's/ *$//')
+
+    if [[ $ECFLOW == true ]]; then
+      COMPILE_NR=$name
+      APP=''
+      ecflow_create_compile_task
+    else
+      echo "Compiling for ${name} with compile option ${NEMS_VER}"
+      #./compile.sh $PATHTR/FV3 $MACHINE_ID "${NEMS_VER}" $name >${LOG_DIR}/compile_${TEST_NAME}_$name.log 2>&1
+      ./compile_cmake.sh $PATHTR $MACHINE_ID "${NEMS_VER}" $name >${LOG_DIR}/compile_${TEST_NAME}_$name.log 2>&1
+      echo "Compiling done for ${name}"
+    fi
+  done
+}
+
 run_utests() {
   for rc in $ut_run_cases; do
     # Load namelist default and override values
@@ -336,7 +391,7 @@ skip_compile=false
 skip_run=false
 
 # Parse command line arguments
-while getopts :c:r:n:ekh opt; do
+while getopts :c:r:n:ekhxz opt; do
   case $opt in
     c)
       run_unit_test=false
@@ -378,6 +433,12 @@ while getopts :c:r:n:ekh opt; do
       ;;
     k)
       keep_rundir=true
+      ;;
+    x)
+      skip_compile=true
+      ;;
+    z)
+      skip_run=true
       ;;
     h)
       usage_and_exit 0
@@ -506,71 +567,54 @@ fi
 ########################################################################
 ####                            COMPILE                             ####
 ########################################################################
-# build_file specifies compilation options
-build_file='utest.bld'
-[[ -f ${build_file} ]] || error "${build_file} does not exist"
+# If skipping compile, check if required executables are in place
+if [[ $skip_compile == true ]]; then
+  number_of_missing_exe=0
+  for name in $ut_compile_cases; do
+    if [[ ! -f ${PATHRT}/fv3_${name}.exe ]]; then
+      echo "Cannot find the required executable file fv3_${name}.exe" >&2
+      number_of_missing_exe=$(( number_of_missing_exe + 1 ))
+    fi
+  done
 
-compile_log=${PATHRT}/Compile_ut_$MACHINE_ID.log
-rm -f fv3_*.exe modules.fv3_* ${compile_log}
-
-while IFS="|" read model comp_opt; do
-  model_found=false
-  model=$(echo $model | sed -e 's/^ *//' -e 's/ *$//')
-  comp_opt=$(echo $comp_opt | sed -e 's/^ *//' -e 's/ *$//')
-  if [[ $model == ${TEST_NAME} ]]; then
-    base_opt=${comp_opt}
-    model_found=true
-    break
-  fi
-done < ${build_file}
-if [[ ${model_found} == false ]]; then
-  error "Build options for $TEST_NAME not found. Please edit utest.bld."
-fi
-
-for name in $ut_compile_cases; do
-  case $name in
-    std)
-      NEMS_VER=${base_opt}
-      ;;
-    32bit)
-      if [[ ${base_opt} =~ "32BIT=Y" ]]; then
-        NEMS_VER=$(echo ${base_opt} | sed -e 's/32BIT=Y/32BIT=N/')
-      elif [[ ${base_opt} =~ "32BIT=N" ]]; then
-        NEMS_VER=$(echo ${base_opt} | sed -e 's/32BIT=N/32BIT=Y/')
-      else
-        NEMS_VER="${base_opt} 32BIT=Y"
-      fi
-      ;;
-    debug)
-      NEMS_VER="${base_opt} 32BIT=Y DEBUG=Y"
-      ;;
-  esac
-  NEMS_VER=$(echo ${NEMS_VER} | sed -e 's/^ *//' -e 's/ *$//')
-
-  if [[ $ECFLOW == true ]]; then
-    COMPILE_NR=$name
-    APP=''
-    ecflow_create_compile_task
+  if [[ $number_of_missing_exe == 0 ]]; then
+    echo "All required executables are found" >&2
   else
-    echo "Compiling for ${name} with compile option ${NEMS_VER}"
-    #./compile.sh $PATHTR/FV3 $MACHINE_ID "${NEMS_VER}" $name >${LOG_DIR}/compile_${TEST_NAME}_$name.log 2>&1
-    ./compile_cmake.sh $PATHTR $MACHINE_ID "${NEMS_VER}" $name >${LOG_DIR}/compile_${TEST_NAME}_$name.log 2>&1
-    echo "Compiling done for ${name}"
+    exit $number_of_missing_exe
   fi
-done
-
+else
+  build_utests
+fi
 ########################################################################
 ####                              RUN                               ####
 ########################################################################
+# If skipping run, stop after compilation. Print information about build
+# status and exit with a non-zero number (equal to the number of failed build)
+if [[ $skip_run == true ]]; then
+  number_of_failed_compilation=0
+  for name in $ut_compile_cases; do
+    if [[ ! -f ${PATHRT}/fv3_${name}.exe ]]; then
+      echo "Failed to generate executable file fv3_${name}.exe" >&2
+      number_of_failed_compilation=$(( number_of_failed_compilation + 1 ))
+    fi
+  done
+
+  if [[ $number_of_failed_compilation == 0 ]]; then
+    echo "All executables have been generated" >&2
+  fi
+
+  exit $number_of_failed_compilation
+fi
+
 mkdir -p ${STMP}/${USER}
 NEW_BASELINE=${STMP}/${USER}/FV3_UT/UNIT_TEST
 RTPWD=$DISKNM/NEMSfv3gfs/develop-20200202
 if [[ $CREATE_BASELINE == true ]]; then
   rm -rf $NEW_BASELINE
   mkdir -p $NEW_BASELINE  
-
-  rsync -a "${RTPWD}"/FV3_* "${NEW_BASELINE}"/
-  rsync -a "${RTPWD}"/WW3_* "${NEW_BASELINE}"/
+  ln -s ${RTPWD}/FV3_input_data ${NEW_BASELINE}
+  #rsync -a "${RTPWD}"/FV3_* "${NEW_BASELINE}"/
+  #rsync -a "${RTPWD}"/WW3_* "${NEW_BASELINE}"/
 fi
 
 # unittest_log is different from REGRESSIONTEST_LOG
@@ -618,7 +662,9 @@ fi
 ####                       UNIT TEST STATUS                         ####
 ########################################################################
 set +e
-cat ${LOG_DIR}/compile_*.log > ${compile_log}
+if [[ $skip_compile == false ]]; then
+  cat ${LOG_DIR}/compile_*.log > ${compile_log}
+fi
 cat ${LOG_DIR}/ut_*.log >> ${unittest_log}
 
 if [[ -e fail_unit_test ]]; then
@@ -631,7 +677,7 @@ if [[ -e fail_unit_test ]]; then
 else
   echo "UNIT TEST WAS SUCCESSFUL" | tee -a ${unittest_log}
 
-  rm -f fv3_*.x fv3_*.exe modules.fv3_*
+  #rm -f fv3_*.x fv3_*.exe modules.fv3_*
   [[ ${keep_rundir} == false ]] && rm -rf ${RUNDIR_ROOT}
 fi
 
