try pull request again (#14)
* First test

* Change branch name

* github event name...

* change to tests/ci dir

* change repo name

* print out stderr

* try recursive checkout

* checkout myself

* in a hurry

* fetch owner id

* Make setup depend on prcheck

* update with fv3 & ccpp/physics updates in order to turn the NSST model on in the coupled model (Replace PR #453) (#483)

* point to fv3 branch
* Add one more test cpld_control_nsst to test added ccpp suite (FV3_GFS_v15p2_couplednsst)
* Modify rt.conf to add FV3_GFS_v15p2_couplednsst
* Modify rt.conf to add a new test, cpld_bmarkfrac_v16_nsst,  remove test cpld_control_nsst
* Modify tests/tests/cpld_bmarkfrac_v16_nsst: 1. cpld_bmarkfrac_v16 to cpld_bmarkfrac_v16_nsst. 2. export NSTF_NAME=2,1,0,0,0 to export nstf_name=2,1,0,0,0.
* Modify input.benchmark_v16.nml.IN & cpld_bmarkfrac_v16_nsst for a consistent definition of nstf_name namelist
* Modify cpld_bmarkfrac_v16_nsst by moving the NSTF_NAME to the namelist field updates section
* RegressionTests_orion.intel.log of the rt run and BL_DATE=20210406 in rt.sh
* RT JOBS PASSED: hera.intel. Log file uploaded.
* run-ci, commit 7 RegressionTest log files
* Push RegressionTests_wcoss_dell_p3.log

Co-authored-by: Brian Curtis <brian.curtis@noaa.gov>

* remove develop

* quiet git commands. run-ci

* Update CMEPS for latest ESCOMP/master; Update PIO to 2.5.2; Refactor modules (#492)


* update ufs for CMEPS master with PIO changes
* update pio to 2.5.2 across platforms
* replace variable SUITE_NAME with CCPP_SUITE
* Merge remote-tracking branch 'DusanJovic/module_common' into feature/updcmeps
* switch to h-nems area on jet

Co-authored-by: Bin Li <Bin.Li@gaea13.ncrc.gov>
Co-authored-by: Dusan Jovic <dusan.jovic@noaa.gov>

* debug this again...

* debug again

* debug continues

* missed repo field

* remove debug related texts

* remove -x flag. run-ci

* reduce sleep time

* diag

* diag2

* Fix pr_uid

* diag again

* still debugging

* lets see if this works

* use context as main yml key

* Try pull request now. run-ci

* minor change. run-ci

* typo fix

* debug 1

* debug2

* minor mods. run-ci

* check another dir

* sleep

* sigh

* sigh2

* increase time again

* test again

Co-authored-by: XuLi-NOAA <55100838+XuLi-NOAA@users.noreply.github.com>
Co-authored-by: Brian Curtis <brian.curtis@noaa.gov>
Co-authored-by: Denise Worthen <denise.worthen@noaa.gov>
Co-authored-by: Bin Li <Bin.Li@gaea13.ncrc.gov>
Co-authored-by: Dusan Jovic <dusan.jovic@noaa.gov>

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -18,41 +18,46 @@ jobs:
       current: ${{ steps.check.outputs.current }}
 
     steps:
-    - name: Check out codes
-      uses: actions/checkout@v2
-
-    - name: Wait until repocheck in aux is complete
-      run: |
-        cd $GITHUB_WORKSPACE/tests/ci
-        url=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs
-        workflow_id=$(curl -sS -H "$app" $url | ./workflow.py ${{ github.run_id }})
-        jobs_url=$(curl -sS -H "$app" $url | ./json_helper.py get_jobs_url $workflow_id)
-        echo "jobs_url is $jobs_url"
-        conclusion=$(echo $jobs_url | ./job_status_check.py "Aux check if repos are up to date")
-        if [[ $conclusion == "failure" ]]; then
-          exit 1
-        else
-          sleep 20
-        fi
+#    - name: Check out codes
+#      uses: actions/checkout@v2
+#
+#    - name: Wait until repocheck in aux is complete
+#      run: |
+#        cd $GITHUB_WORKSPACE/tests/ci
+#        url=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs
+#        workflow_id=$(curl -sS -H "$app" $url | ./workflow.py ${{ github.run_id }})
+#        jobs_url=$(curl -sS -H "$app" $url | ./json_helper.py get_jobs_url $workflow_id)
+#        echo "jobs_url is $jobs_url"
+#        conclusion=$(echo $jobs_url | ./job_status_check.py "Aux check if repos are up to date")
+#        if [[ $conclusion == "failure" ]]; then
+#          exit 1
+#        else
+#          sleep 20
+#        fi
+#
+    - name: sleep
+      run: sleep 90
 
     - name: Retrieve repocheck result
       uses: actions/cache@v2
       with:
-        path: cf2
+        path: ${{ github.workspace }}/cf2
         key: repocheck-${{ github.run_id }}
 
-    - name: Set the result flag
-      id: check
+    - name: Set flag
       run: |
         pwd
         ls -alF
         cat cf2
-        repocheck_result=$(cat cf2)
-        if [[ $repocheck_result == success ]]; then
-          echo "::set-output name=current::yes"
-        elif [[ $repocheck_result == failure ]]; then
-          echo "::set-output name=current::no"
-        fi
+        cd $GITHUB_WORKSPACE
+        ls -alF
+
+#        repocheck_result=$(cat cf2)
+#        if [[ $repocheck_result == success ]]; then
+#          echo "::set-output name=current::yes"
+#        elif [[ $repocheck_result == failure ]]; then
+#          echo "::set-output name=current::no"
+#        fi
 
   runcheck:
     name: Check if run-ci is requested
